# Site settings
title: Belchak.com
email: ben@belchak.com
description: >
    A blog about technology and leadership, and sometimes about leadership in
    technology.
baseurl: "" # the subpath of your site, e.g. /blog/

disqus_shortname: belchakcom

# Build settings
markdown: kramdown

gems:
  - octopress-image-tag
  - octopress-video-tag
  - octopress-codeblock
  - octopress-quote-tag
  - octopress-codefence
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://www.belchak.com

# Owner/author information
owner:
  name:           Ben Belchak
  avatar:         avatar.jpg
  bio:            "Husband, father of four, Head of Site Reliability Engineering at Shazam. American in London."
  email:          ben@belchak.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:       BenBelchak
  facebook:      hekman
  github:        bbelchak
  stackexchange: ben-belchak
  linkedin:      belchak
  instagram:     bbelchak
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-20863470-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: pygments
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
